// Package resolvers contains the GraphQL resolver implementation for the
// api-gateway. The per-schema resolver files (schema.resolvers.go) are
// generated by gqlgen; this file holds the hand-written root Resolver.
package resolvers

import (
	greenhousev1 "github.com/greenhouse-monorepo/libs/models-go/gen/greenhouse/v1"
)

// Resolver is the gqlgen root resolver. It is a Backend-for-Frontend: each
// GraphQL field resolver fans out to one of the internal gRPC services.
type Resolver struct {
	Telemetry greenhousev1.TelemetryServiceClient
	Anomaly   greenhousev1.AnomalyDetectionServiceClient
}
