package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/greenhouse-monorepo/services/api-gateway/internal/graph"
)

// RegisterSensor is the resolver for the registerSensor field.
func (r *mutationResolver) RegisterSensor(ctx context.Context, zoneID string, typeArg graph.SensorType, unit string) (*graph.Sensor, error) {
	panic(fmt.Errorf("not implemented: RegisterSensor - registerSensor"))
}

// Greenhouses is the resolver for the greenhouses field.
func (r *queryResolver) Greenhouses(ctx context.Context) ([]*graph.Greenhouse, error) {
	panic(fmt.Errorf("not implemented: Greenhouses - greenhouses"))
}

// Greenhouse is the resolver for the greenhouse field.
func (r *queryResolver) Greenhouse(ctx context.Context, id string) (*graph.Greenhouse, error) {
	panic(fmt.Errorf("not implemented: Greenhouse - greenhouse"))
}

// Anomalies is the resolver for the anomalies field.
func (r *queryResolver) Anomalies(ctx context.Context, greenhouseID string) ([]*graph.Anomaly, error) {
	panic(fmt.Errorf("not implemented: Anomalies - anomalies"))
}

// Readings is the resolver for the readings field.
func (r *subscriptionResolver) Readings(ctx context.Context, zoneID string) (<-chan *graph.SensorReading, error) {
	panic(fmt.Errorf("not implemented: Readings - readings"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// Subscription returns graph.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graph.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
