// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Anomaly struct {
	SensorID    string          `json:"sensorId"`
	Severity    AnomalySeverity `json:"severity"`
	Description string          `json:"description"`
	Score       float64         `json:"score"`
	DetectedAt  time.Time       `json:"detectedAt"`
}

type Greenhouse struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Location string  `json:"location"`
	Zones    []*Zone `json:"zones"`
}

type Mutation struct {
}

type Query struct {
}

type Sensor struct {
	ID            string         `json:"id"`
	Type          SensorType     `json:"type"`
	Unit          string         `json:"unit"`
	LatestReading *SensorReading `json:"latestReading,omitempty"`
}

type SensorReading struct {
	SensorID   string     `json:"sensorId"`
	Type       SensorType `json:"type"`
	Value      float64    `json:"value"`
	Unit       string     `json:"unit"`
	ObservedAt time.Time  `json:"observedAt"`
}

type Subscription struct {
}

type Zone struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Crop    string    `json:"crop"`
	Sensors []*Sensor `json:"sensors"`
}

type AnomalySeverity string

const (
	AnomalySeverityInfo     AnomalySeverity = "INFO"
	AnomalySeverityWarning  AnomalySeverity = "WARNING"
	AnomalySeverityCritical AnomalySeverity = "CRITICAL"
)

var AllAnomalySeverity = []AnomalySeverity{
	AnomalySeverityInfo,
	AnomalySeverityWarning,
	AnomalySeverityCritical,
}

func (e AnomalySeverity) IsValid() bool {
	switch e {
	case AnomalySeverityInfo, AnomalySeverityWarning, AnomalySeverityCritical:
		return true
	}
	return false
}

func (e AnomalySeverity) String() string {
	return string(e)
}

func (e *AnomalySeverity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnomalySeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnomalySeverity", str)
	}
	return nil
}

func (e AnomalySeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AnomalySeverity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AnomalySeverity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SensorType string

const (
	SensorTypeTemperature  SensorType = "TEMPERATURE"
	SensorTypeHumidity     SensorType = "HUMIDITY"
	SensorTypeSoilMoisture SensorType = "SOIL_MOISTURE"
	SensorTypeCo2          SensorType = "CO2"
	SensorTypeLight        SensorType = "LIGHT"
)

var AllSensorType = []SensorType{
	SensorTypeTemperature,
	SensorTypeHumidity,
	SensorTypeSoilMoisture,
	SensorTypeCo2,
	SensorTypeLight,
}

func (e SensorType) IsValid() bool {
	switch e {
	case SensorTypeTemperature, SensorTypeHumidity, SensorTypeSoilMoisture, SensorTypeCo2, SensorTypeLight:
		return true
	}
	return false
}

func (e SensorType) String() string {
	return string(e)
}

func (e *SensorType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SensorType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SensorType", str)
	}
	return nil
}

func (e SensorType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SensorType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SensorType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
