# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greenhouse/v1/anomaly.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'greenhouse/v1/anomaly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from greenhouse.v1 import telemetry_pb2 as greenhouse_dot_v1_dot_telemetry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgreenhouse/v1/anomaly.proto\x12\rgreenhouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dgreenhouse/v1/telemetry.proto\"\xa5\x02\n\x07\x41nomaly\x12\x1b\n\tsensor_id\x18\x01 \x01(\tR\x08sensorId\x12:\n\x08severity\x18\x02 \x01(\x0e\x32\x1e.greenhouse.v1.AnomalySeverityR\x08severity\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12%\n\x0eobserved_value\x18\x04 \x01(\x01R\robservedValue\x12%\n\x0e\x65xpected_value\x18\x05 \x01(\x01R\rexpectedValue\x12\x14\n\x05score\x18\x06 \x01(\x01R\x05score\x12;\n\x0b\x64\x65tected_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ndetectedAt\"R\n\x16\x44\x65tectAnomaliesRequest\x12\x38\n\x08readings\x18\x01 \x03(\x0b\x32\x1c.greenhouse.v1.SensorReadingR\x08readings\"O\n\x17\x44\x65tectAnomaliesResponse\x12\x34\n\tanomalies\x18\x01 \x03(\x0b\x32\x16.greenhouse.v1.AnomalyR\tanomalies*\x8b\x01\n\x0f\x41nomalySeverity\x12 \n\x1c\x41NOMALY_SEVERITY_UNSPECIFIED\x10\x00\x12\x19\n\x15\x41NOMALY_SEVERITY_INFO\x10\x01\x12\x1c\n\x18\x41NOMALY_SEVERITY_WARNING\x10\x02\x12\x1d\n\x19\x41NOMALY_SEVERITY_CRITICAL\x10\x03\x32{\n\x17\x41nomalyDetectionService\x12`\n\x0f\x44\x65tectAnomalies\x12%.greenhouse.v1.DetectAnomaliesRequest\x1a&.greenhouse.v1.DetectAnomaliesResponseB\xc4\x01\n\x11\x63om.greenhouse.v1B\x0c\x41nomalyProtoP\x01ZLgithub.com/greenhouse-monorepo/libs/models-go/gen/greenhouse/v1;greenhousev1\xa2\x02\x03GXX\xaa\x02\rGreenhouse.V1\xca\x02\rGreenhouse\\V1\xe2\x02\x19Greenhouse\\V1\\GPBMetadata\xea\x02\x0eGreenhouse::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greenhouse.v1.anomaly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.greenhouse.v1B\014AnomalyProtoP\001ZLgithub.com/greenhouse-monorepo/libs/models-go/gen/greenhouse/v1;greenhousev1\242\002\003GXX\252\002\rGreenhouse.V1\312\002\rGreenhouse\\V1\342\002\031Greenhouse\\V1\\GPBMetadata\352\002\016Greenhouse::V1'
  _globals['_ANOMALYSEVERITY']._serialized_start=572
  _globals['_ANOMALYSEVERITY']._serialized_end=711
  _globals['_ANOMALY']._serialized_start=111
  _globals['_ANOMALY']._serialized_end=404
  _globals['_DETECTANOMALIESREQUEST']._serialized_start=406
  _globals['_DETECTANOMALIESREQUEST']._serialized_end=488
  _globals['_DETECTANOMALIESRESPONSE']._serialized_start=490
  _globals['_DETECTANOMALIESRESPONSE']._serialized_end=569
  _globals['_ANOMALYDETECTIONSERVICE']._serialized_start=713
  _globals['_ANOMALYDETECTIONSERVICE']._serialized_end=836
# @@protoc_insertion_point(module_scope)
