# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from greenhouse.v1 import anomaly_pb2 as greenhouse_dot_v1_dot_anomaly__pb2


class AnomalyDetectionServiceStub(object):
    """Implemented by the Python anomaly-detector ML module. The Go api-gateway
    calls it to score incoming telemetry.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectAnomalies = channel.unary_unary(
                '/greenhouse.v1.AnomalyDetectionService/DetectAnomalies',
                request_serializer=greenhouse_dot_v1_dot_anomaly__pb2.DetectAnomaliesRequest.SerializeToString,
                response_deserializer=greenhouse_dot_v1_dot_anomaly__pb2.DetectAnomaliesResponse.FromString,
                _registered_method=True)


class AnomalyDetectionServiceServicer(object):
    """Implemented by the Python anomaly-detector ML module. The Go api-gateway
    calls it to score incoming telemetry.
    """

    def DetectAnomalies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnomalyDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectAnomalies': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAnomalies,
                    request_deserializer=greenhouse_dot_v1_dot_anomaly__pb2.DetectAnomaliesRequest.FromString,
                    response_serializer=greenhouse_dot_v1_dot_anomaly__pb2.DetectAnomaliesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greenhouse.v1.AnomalyDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('greenhouse.v1.AnomalyDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnomalyDetectionService(object):
    """Implemented by the Python anomaly-detector ML module. The Go api-gateway
    calls it to score incoming telemetry.
    """

    @staticmethod
    def DetectAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greenhouse.v1.AnomalyDetectionService/DetectAnomalies',
            greenhouse_dot_v1_dot_anomaly__pb2.DetectAnomaliesRequest.SerializeToString,
            greenhouse_dot_v1_dot_anomaly__pb2.DetectAnomaliesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
