# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greenhouse/v1/greenhouse.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'greenhouse/v1/greenhouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egreenhouse/v1/greenhouse.proto\x12\rgreenhouse.v1\"w\n\nGreenhouse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n\x08location\x18\x03 \x01(\tR\x08location\x12)\n\x05zones\x18\x04 \x03(\x0b\x32\x13.greenhouse.v1.ZoneR\x05zones\"\x94\x01\n\x04Zone\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12#\n\rgreenhouse_id\x18\x02 \x01(\tR\x0cgreenhouseId\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n\x04\x63rop\x18\x04 \x01(\tR\x04\x63rop\x12/\n\x07sensors\x18\x05 \x03(\x0b\x32\x15.greenhouse.v1.SensorR\x07sensors\"t\n\x06Sensor\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n\x07zone_id\x18\x02 \x01(\tR\x06zoneId\x12-\n\x04type\x18\x03 \x01(\x0e\x32\x19.greenhouse.v1.SensorTypeR\x04type\x12\x12\n\x04unit\x18\x04 \x01(\tR\x04unit*\xab\x01\n\nSensorType\x12\x1b\n\x17SENSOR_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17SENSOR_TYPE_TEMPERATURE\x10\x01\x12\x18\n\x14SENSOR_TYPE_HUMIDITY\x10\x02\x12\x1d\n\x19SENSOR_TYPE_SOIL_MOISTURE\x10\x03\x12\x13\n\x0fSENSOR_TYPE_CO2\x10\x04\x12\x15\n\x11SENSOR_TYPE_LIGHT\x10\x05\x42\xc7\x01\n\x11\x63om.greenhouse.v1B\x0fGreenhouseProtoP\x01ZLgithub.com/greenhouse-monorepo/libs/models-go/gen/greenhouse/v1;greenhousev1\xa2\x02\x03GXX\xaa\x02\rGreenhouse.V1\xca\x02\rGreenhouse\\V1\xe2\x02\x19Greenhouse\\V1\\GPBMetadata\xea\x02\x0eGreenhouse::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greenhouse.v1.greenhouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.greenhouse.v1B\017GreenhouseProtoP\001ZLgithub.com/greenhouse-monorepo/libs/models-go/gen/greenhouse/v1;greenhousev1\242\002\003GXX\252\002\rGreenhouse.V1\312\002\rGreenhouse\\V1\342\002\031Greenhouse\\V1\\GPBMetadata\352\002\016Greenhouse::V1'
  _globals['_SENSORTYPE']._serialized_start=440
  _globals['_SENSORTYPE']._serialized_end=611
  _globals['_GREENHOUSE']._serialized_start=49
  _globals['_GREENHOUSE']._serialized_end=168
  _globals['_ZONE']._serialized_start=171
  _globals['_ZONE']._serialized_end=319
  _globals['_SENSOR']._serialized_start=321
  _globals['_SENSOR']._serialized_end=437
# @@protoc_insertion_point(module_scope)
