# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greenhouse/v1/telemetry.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'greenhouse/v1/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from greenhouse.v1 import greenhouse_pb2 as greenhouse_dot_v1_dot_greenhouse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgreenhouse/v1/telemetry.proto\x12\rgreenhouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egreenhouse/v1/greenhouse.proto\"\xc2\x01\n\rSensorReading\x12\x1b\n\tsensor_id\x18\x01 \x01(\tR\x08sensorId\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x19.greenhouse.v1.SensorTypeR\x04type\x12\x14\n\x05value\x18\x03 \x01(\x01R\x05value\x12\x12\n\x04unit\x18\x04 \x01(\tR\x04unit\x12;\n\x0bobserved_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\nobservedAt\"Q\n\x15IngestReadingsRequest\x12\x38\n\x08readings\x18\x01 \x03(\x0b\x32\x1c.greenhouse.v1.SensorReadingR\x08readings\"P\n\x16IngestReadingsResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\rR\x08\x61\x63\x63\x65pted\x12\x1a\n\x08rejected\x18\x02 \x01(\rR\x08rejected\"O\n\x15StreamReadingsRequest\x12\x36\n\x07reading\x18\x01 \x01(\x0b\x32\x1c.greenhouse.v1.SensorReadingR\x07reading\"P\n\x16StreamReadingsResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\rR\x08\x61\x63\x63\x65pted\x12\x1a\n\x08rejected\x18\x02 \x01(\rR\x08rejected\"6\n\x17GetLatestReadingRequest\x12\x1b\n\tsensor_id\x18\x01 \x01(\tR\x08sensorId\"R\n\x18GetLatestReadingResponse\x12\x36\n\x07reading\x18\x01 \x01(\x0b\x32\x1c.greenhouse.v1.SensorReadingR\x07reading2\xb7\x02\n\x10TelemetryService\x12]\n\x0eIngestReadings\x12$.greenhouse.v1.IngestReadingsRequest\x1a%.greenhouse.v1.IngestReadingsResponse\x12_\n\x0eStreamReadings\x12$.greenhouse.v1.StreamReadingsRequest\x1a%.greenhouse.v1.StreamReadingsResponse(\x01\x12\x63\n\x10GetLatestReading\x12&.greenhouse.v1.GetLatestReadingRequest\x1a\'.greenhouse.v1.GetLatestReadingResponseB\xc6\x01\n\x11\x63om.greenhouse.v1B\x0eTelemetryProtoP\x01ZLgithub.com/greenhouse-monorepo/libs/models-go/gen/greenhouse/v1;greenhousev1\xa2\x02\x03GXX\xaa\x02\rGreenhouse.V1\xca\x02\rGreenhouse\\V1\xe2\x02\x19Greenhouse\\V1\\GPBMetadata\xea\x02\x0eGreenhouse::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greenhouse.v1.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.greenhouse.v1B\016TelemetryProtoP\001ZLgithub.com/greenhouse-monorepo/libs/models-go/gen/greenhouse/v1;greenhousev1\242\002\003GXX\252\002\rGreenhouse.V1\312\002\rGreenhouse\\V1\342\002\031Greenhouse\\V1\\GPBMetadata\352\002\016Greenhouse::V1'
  _globals['_SENSORREADING']._serialized_start=114
  _globals['_SENSORREADING']._serialized_end=308
  _globals['_INGESTREADINGSREQUEST']._serialized_start=310
  _globals['_INGESTREADINGSREQUEST']._serialized_end=391
  _globals['_INGESTREADINGSRESPONSE']._serialized_start=393
  _globals['_INGESTREADINGSRESPONSE']._serialized_end=473
  _globals['_STREAMREADINGSREQUEST']._serialized_start=475
  _globals['_STREAMREADINGSREQUEST']._serialized_end=554
  _globals['_STREAMREADINGSRESPONSE']._serialized_start=556
  _globals['_STREAMREADINGSRESPONSE']._serialized_end=636
  _globals['_GETLATESTREADINGREQUEST']._serialized_start=638
  _globals['_GETLATESTREADINGREQUEST']._serialized_end=692
  _globals['_GETLATESTREADINGRESPONSE']._serialized_start=694
  _globals['_GETLATESTREADINGRESPONSE']._serialized_end=776
  _globals['_TELEMETRYSERVICE']._serialized_start=779
  _globals['_TELEMETRYSERVICE']._serialized_end=1090
# @@protoc_insertion_point(module_scope)
