# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from greenhouse.v1 import telemetry_pb2 as greenhouse_dot_v1_dot_telemetry__pb2


class TelemetryServiceStub(object):
    """Implemented by the Go ingest-service. Field gateways stream sensor
    readings in; other services query the latest known value.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestReadings = channel.unary_unary(
                '/greenhouse.v1.TelemetryService/IngestReadings',
                request_serializer=greenhouse_dot_v1_dot_telemetry__pb2.IngestReadingsRequest.SerializeToString,
                response_deserializer=greenhouse_dot_v1_dot_telemetry__pb2.IngestReadingsResponse.FromString,
                _registered_method=True)
        self.StreamReadings = channel.stream_unary(
                '/greenhouse.v1.TelemetryService/StreamReadings',
                request_serializer=greenhouse_dot_v1_dot_telemetry__pb2.StreamReadingsRequest.SerializeToString,
                response_deserializer=greenhouse_dot_v1_dot_telemetry__pb2.StreamReadingsResponse.FromString,
                _registered_method=True)
        self.GetLatestReading = channel.unary_unary(
                '/greenhouse.v1.TelemetryService/GetLatestReading',
                request_serializer=greenhouse_dot_v1_dot_telemetry__pb2.GetLatestReadingRequest.SerializeToString,
                response_deserializer=greenhouse_dot_v1_dot_telemetry__pb2.GetLatestReadingResponse.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """Implemented by the Go ingest-service. Field gateways stream sensor
    readings in; other services query the latest known value.
    """

    def IngestReadings(self, request, context):
        """Bulk ingest of buffered readings from a field gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReadings(self, request_iterator, context):
        """Client-streaming push for always-connected edge devices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestReading(self, request, context):
        """Latest reading for a sensor, consumed by the api-gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestReadings': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestReadings,
                    request_deserializer=greenhouse_dot_v1_dot_telemetry__pb2.IngestReadingsRequest.FromString,
                    response_serializer=greenhouse_dot_v1_dot_telemetry__pb2.IngestReadingsResponse.SerializeToString,
            ),
            'StreamReadings': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamReadings,
                    request_deserializer=greenhouse_dot_v1_dot_telemetry__pb2.StreamReadingsRequest.FromString,
                    response_serializer=greenhouse_dot_v1_dot_telemetry__pb2.StreamReadingsResponse.SerializeToString,
            ),
            'GetLatestReading': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestReading,
                    request_deserializer=greenhouse_dot_v1_dot_telemetry__pb2.GetLatestReadingRequest.FromString,
                    response_serializer=greenhouse_dot_v1_dot_telemetry__pb2.GetLatestReadingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greenhouse.v1.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('greenhouse.v1.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """Implemented by the Go ingest-service. Field gateways stream sensor
    readings in; other services query the latest known value.
    """

    @staticmethod
    def IngestReadings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greenhouse.v1.TelemetryService/IngestReadings',
            greenhouse_dot_v1_dot_telemetry__pb2.IngestReadingsRequest.SerializeToString,
            greenhouse_dot_v1_dot_telemetry__pb2.IngestReadingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReadings(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/greenhouse.v1.TelemetryService/StreamReadings',
            greenhouse_dot_v1_dot_telemetry__pb2.StreamReadingsRequest.SerializeToString,
            greenhouse_dot_v1_dot_telemetry__pb2.StreamReadingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greenhouse.v1.TelemetryService/GetLatestReading',
            greenhouse_dot_v1_dot_telemetry__pb2.GetLatestReadingRequest.SerializeToString,
            greenhouse_dot_v1_dot_telemetry__pb2.GetLatestReadingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
