python_requirement(name="numpy", requirements=["numpy>=2.0"])
python_requirement(name="scikit-learn", requirements=["scikit-learn>=1.5"])
python_requirement(name="types-protobuf", requirements=["types-protobuf"])
